# Generated by Django 3.1.3 on 2020-12-10 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fire_weather_index', models.CharField(max_length=5)),
                ('date', models.TextField()),
            ],
        ),
    ]
